In [27]:
d1 = { 'key1' : [2,3,4,5,6,7,8] , 
     'key2' : [12,13,14,15,16,17,18] ,
     'key3' : [21,22,23,24,25,26,27],
     'key4' : [31,32,33,34,35,36,37],
     'key5' : [41,42,43,44,45,46,47]}

In [28]:
# To convert the dict into frames

import pandas as p 
df2 = p.DataFrame(d1)

In [29]:
d3 = { 'key1' : [2,3,4,5,6,7] , 
     'key2' : [12,13,14,15,16,17,18] ,
     'key3' : [21,22,23,24,25,26,27],
     'key4' : [31,32,33,34,35,36,37],
     'key5' : [41,42,43,44,45,46,47]}

In [30]:
import pandas as p 
p.DataFrame(d3)
# Keep in mind while converting the dict into frame
#  All arrays must be of the same length

ValueError: All arrays must be of the same length

In [31]:
d4 = { 'key1' : [2,3,4,5,6,7,8] , 
     'key2' : [12,"gharad",14,15,"patil",17,18] ,
     'key3' : [21,22,23,24,25,"mahendra",27],
     'key4' : [31,32,"mohit",34,35,36,37],
     'key5' : [41,42,43,44,45,"rahul",47]}

In [32]:
df5 = p.DataFrame(d4)

In [33]:
df2

key1  key2  key3  key4  key5
0     2    12    21    31    41
1     3    13    22    32    42
2     4    14    23    33    43
3     5    15    24    34    44
4     6    16    25    35    45
5     7    17    26    36    46
6     8    18    27    37    47

In [34]:
df5

key1    key2      key3   key4   key5
0     2      12        21     31     41
1     3  gharad        22     32     42
2     4      14        23  mohit     43
3     5      15        24     34     44
4     6   patil        25     35     45
5     7      17  mahendra     36  rahul
6     8      18        27     37     47

In [35]:
p.merge(df2,df5)
#        L   R
# If we are not set that how the merge operation is going to perform 
# Then by default it peform inner merge operation (Intersection) 
# In the inner merge operation it gives us the values 
# Which are same in both data sets


key1 key2 key3 key4 key5
0     2   12   21   31   41
1     5   15   24   34   44
2     8   18   27   37   47

In [36]:
p.merge(df2,df5 , how = "inner" , on = "key1")

key1  key2_x  key3_x  key4_x  key5_x  key2_y    key3_y key4_y key5_y
0     2      12      21      31      41      12        21     31     41
1     3      13      22      32      42  gharad        22     32     42
2     4      14      23      33      43      14        23  mohit     43
3     5      15      24      34      44      15        24     34     44
4     6      16      25      35      45   patil        25     35     45
5     7      17      26      36      46      17  mahendra     36  rahul
6     8      18      27      37      47      18        27     37     47

In [37]:
p.merge(df2,df5 , how = "inner" , on = "key5")

key1_x  key2_x  key3_x  key4_x key5  key1_y  key2_y key3_y key4_y
0       2      12      21      31   41       2      12     21     31
1       3      13      22      32   42       3  gharad     22     32
2       4      14      23      33   43       4      14     23  mohit
3       5      15      24      34   44       5      15     24     34
4       6      16      25      35   45       6   patil     25     35
5       8      18      27      37   47       8      18     27     37

In [39]:
df2

key1  key2  key3  key4  key5
0     2    12    21    31    41
1     3    13    22    32    42
2     4    14    23    33    43
3     5    15    24    34    44
4     6    16    25    35    45
5     7    17    26    36    46
6     8    18    27    37    47

In [40]:
df5

key1    key2      key3   key4   key5
0     2      12        21     31     41
1     3  gharad        22     32     42
2     4      14        23  mohit     43
3     5      15        24     34     44
4     6   patil        25     35     45
5     7      17  mahendra     36  rahul
6     8      18        27     37     47

In [38]:
p.merge(df2,df5 , how = "left" , on = "key5")
#        L   R
# In the left join it bring all the data from left table 
# Inside this the on operation is based on the macthing if 
# If the data is going to match then then it the data from dataset

key1_x  key2_x  key3_x  key4_x key5  key1_y  key2_y key3_y key4_y
0       2      12      21      31   41     2.0      12     21     31
1       3      13      22      32   42     3.0  gharad     22     32
2       4      14      23      33   43     4.0      14     23  mohit
3       5      15      24      34   44     5.0      15     24     34
4       6      16      25      35   45     6.0   patil     25     35
5       7      17      26      36   46     NaN     NaN    NaN    NaN
6       8      18      27      37   47     8.0      18     27     37

In [42]:
p.merge(df2,df5 , how = "right" , on = "key1")
# Inside this it bring all the data from the right table
#  AN the values which are present at the left that is basically dicide 
# By 'On' condition if the values in the key1 is matched with the values present
# in the 'df2' table then it fetch the matching rows from the both table 

key1  key2_x  key3_x  key4_x  key5_x  key2_y    key3_y key4_y key5_y
0     2      12      21      31      41      12        21     31     41
1     3      13      22      32      42  gharad        22     32     42
2     4      14      23      33      43      14        23  mohit     43
3     5      15      24      34      44      15        24     34     44
4     6      16      25      35      45   patil        25     35     45
5     7      17      26      36      46      17  mahendra     36  rahul
6     8      18      27      37      47      18        27     37     47

In [43]:
p.merge(df2,df5 , how = "outer" , on = "key5")
# Outer will try to bring every combination from the left table and right table

C:\Users\mahen\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:916: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  key_col = Index(lvals).where(~mask_left, rvals)


key1_x  key2_x  key3_x  key4_x   key5  key1_y  key2_y    key3_y key4_y
0     2.0    12.0    21.0    31.0   41.0     2.0      12        21     31
1     3.0    13.0    22.0    32.0   42.0     3.0  gharad        22     32
2     4.0    14.0    23.0    33.0   43.0     4.0      14        23  mohit
3     5.0    15.0    24.0    34.0   44.0     5.0      15        24     34
4     6.0    16.0    25.0    35.0   45.0     6.0   patil        25     35
5     7.0    17.0    26.0    36.0   46.0     NaN     NaN       NaN    NaN
6     8.0    18.0    27.0    37.0   47.0     8.0      18        27     37
7     NaN     NaN     NaN     NaN  rahul     7.0      17  mahendra     36

In [ ]:
we can aslo use 'On' condition for multiple keys as follows :

In [44]:
p.merge(df2,df5 , how = "outer" , on = ["key5" , "key4"])

C:\Users\mahen\anaconda3\lib\site-packages\pandas\core\reshape\merge.py:916: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  key_col = Index(lvals).where(~mask_left, rvals)


key1_x  key2_x  key3_x   key4   key5  key1_y  key2_y    key3_y
0     2.0    12.0    21.0   31.0   41.0     2.0      12        21
1     3.0    13.0    22.0   32.0   42.0     3.0  gharad        22
2     4.0    14.0    23.0   33.0   43.0     NaN     NaN       NaN
3     5.0    15.0    24.0   34.0   44.0     5.0      15        24
4     6.0    16.0    25.0   35.0   45.0     6.0   patil        25
5     7.0    17.0    26.0   36.0   46.0     NaN     NaN       NaN
6     8.0    18.0    27.0   37.0   47.0     8.0      18        27
7     NaN     NaN     NaN  mohit     43     4.0      14        23
8     NaN     NaN     NaN     36  rahul     7.0      17  mahendra

In [ ]:
we can aslo use right_on left_on in case if we have datasets with diff names of columns

In [62]:
d11 = {'a':[1,2,3,4,5,"sudh"],
      'b' : [7,8,9,10,11,12],
      'c':[13,14,15,16,17,18],
      'd':[19,20,21,22,23,24]
}
d12 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"ineuron","pwskills",24]
}

In [ ]:
When have diff data sets with diff colomn names

In [63]:
df11 = p.DataFrame(d11)

In [64]:
df12 = p.DataFrame(d12)

In [65]:
df11

a   b   c   d
0     1   7  13  19
1     2   8  14  20
2     3   9  15  21
3     4  10  16  22
4     5  11  17  23
5  sudh  12  18  24

In [67]:
df12

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   ineuron
4     5     11    17  pwskills
5  sudh     12    18        24

In [70]:
p.merge(df11,df12 , how = 'left' , left_on = 'a' , right_on = 'key1')
# When how = 'left' it always try to fetch the data from the left table based on
# left_on and right_on condition 

a   b   c   d  key1   key2  key3      key4
0     1   7  13  19     1      7    13        19
1     2   8  14  20     2      8    14        20
2     3   9  15  21     3  kumar    15        21
3     4  10  16  22     4     10    16   ineuron
4     5  11  17  23     5     11    17  pwskills
5  sudh  12  18  24  sudh     12    18        24

In [72]:
p.merge(df11,df12 , how = 'right' , left_on = 'd' , right_on = 'key4')

a     b     c    d  key1   key2  key3      key4
0     1   7.0  13.0   19     1      7    13        19
1     2   8.0  14.0   20     2      8    14        20
2     3   9.0  15.0   21     3  kumar    15        21
3   NaN   NaN   NaN  NaN     4     10    16   ineuron
4   NaN   NaN   NaN  NaN     5     11    17  pwskills
5  sudh  12.0  18.0   24  sudh     12    18        24

In [73]:
p.merge(df11,df12 , how = 'outer' , left_on = 'a' , right_on = 'key1')

a   b   c   d  key1   key2  key3      key4
0     1   7  13  19     1      7    13        19
1     2   8  14  20     2      8    14        20
2     3   9  15  21     3  kumar    15        21
3     4  10  16  22     4     10    16   ineuron
4     5  11  17  23     5     11    17  pwskills
5  sudh  12  18  24  sudh     12    18        24

In [74]:
p.merge(df11,df12 , how = 'outer' , left_on = 'a' , right_on = 'key3')

a     b     c     d  key1   key2  key3      key4
0      1   7.0  13.0  19.0   NaN    NaN   NaN       NaN
1      2   8.0  14.0  20.0   NaN    NaN   NaN       NaN
2      3   9.0  15.0  21.0   NaN    NaN   NaN       NaN
3      4  10.0  16.0  22.0   NaN    NaN   NaN       NaN
4      5  11.0  17.0  23.0   NaN    NaN   NaN       NaN
5   sudh  12.0  18.0  24.0   NaN    NaN   NaN       NaN
6    NaN   NaN   NaN   NaN     1      7  13.0        19
7    NaN   NaN   NaN   NaN     2      8  14.0        20
8    NaN   NaN   NaN   NaN     3  kumar  15.0        21
9    NaN   NaN   NaN   NaN     4     10  16.0   ineuron
10   NaN   NaN   NaN   NaN     5     11  17.0  pwskills
11   NaN   NaN   NaN   NaN  sudh     12  18.0        24

In [75]:
df11.join(df12)

a   b   c   d  key1   key2  key3      key4
0     1   7  13  19     1      7    13        19
1     2   8  14  20     2      8    14        20
2     3   9  15  21     3  kumar    15        21
3     4  10  16  22     4     10    16   ineuron
4     5  11  17  23     5     11    17  pwskills
5  sudh  12  18  24  sudh     12    18        24

In [76]:
d14 = {'a':[1,2,3,4,5,"sudh"],
      'b' : [7,8,9,10,11,12],
      'c':[13,14,15,16,17,18],
      'd':[19,20,21,22,23,24]
}
d15 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"ineuron","pwskills",24]
}

In [82]:
df16 = p.DataFrame(d14 , index = [1,2,3,4,5,6])

In [88]:
df17 = p.DataFrame(d15 , index = [1,2,3,4,5,'F'])

In [89]:
df16

a   b   c   d
1     1   7  13  19
2     2   8  14  20
3     3   9  15  21
4     4  10  16  22
5     5  11  17  23
6  sudh  12  18  24

In [90]:
df17

key1   key2  key3      key4
1     1      7    13        19
2     2      8    14        20
3     3  kumar    15        21
4     4     10    16   ineuron
5     5     11    17  pwskills
F  sudh     12    18        24

In [91]:
df16.join(df17 ,how ='right') 
# It bringing all the data from the right hand side and put 
# that data at the right side
# And the values which are avialable at the left hand side that are decide by matching
# Indexes if the index is matched then the values are going to be append at the left hand side of the table 
# If the indexes are matched then it append the values as NaN 

a     b     c     d  key1   key2  key3      key4
1    1   7.0  13.0  19.0     1      7    13        19
2    2   8.0  14.0  20.0     2      8    14        20
3    3   9.0  15.0  21.0     3  kumar    15        21
4    4  10.0  16.0  22.0     4     10    16   ineuron
5    5  11.0  17.0  23.0     5     11    17  pwskills
F  NaN   NaN   NaN   NaN  sudh     12    18        24

In [92]:
df16.join(df17 , how = 'left')
# It bringing all the data from the left hand side and put 
# that data at the left side
# And the values which are avialable at the right hand side that are decide by matching
# Indexes if the index is matched then the values are going to be append at the right hand side of the table 
# If the indexes are matched then it append the values as NaN 

a   b   c   d key1   key2  key3      key4
1     1   7  13  19    1      7  13.0        19
2     2   8  14  20    2      8  14.0        20
3     3   9  15  21    3  kumar  15.0        21
4     4  10  16  22    4     10  16.0   ineuron
5     5  11  17  23    5     11  17.0  pwskills
6  sudh  12  18  24  NaN    NaN   NaN       NaN

In [93]:
df16.join(df17 , how = 'outer')
# It takes all the combinations and then try to create the data

a     b     c     d  key1   key2  key3      key4
1     1   7.0  13.0  19.0     1      7  13.0        19
2     2   8.0  14.0  20.0     2      8  14.0        20
3     3   9.0  15.0  21.0     3  kumar  15.0        21
4     4  10.0  16.0  22.0     4     10  16.0   ineuron
5     5  11.0  17.0  23.0     5     11  17.0  pwskills
6  sudh  12.0  18.0  24.0   NaN    NaN   NaN       NaN
F   NaN   NaN   NaN   NaN  sudh     12  18.0        24

In [94]:
df16.join(df17 , how = 'inner')
# It simply create the data with matching values those values which are 
# matched in both tables

a   b   c   d key1   key2  key3      key4
1  1   7  13  19    1      7    13        19
2  2   8  14  20    2      8    14        20
3  3   9  15  21    3  kumar    15        21
4  4  10  16  22    4     10    16   ineuron
5  5  11  17  23    5     11    17  pwskills

In [ ]:
If we are not pass how while joining operation then it by default takes 
join the datasets as left join

In [ ]:
join perform operations based on index values and

merge perform operations based on columns values 

In [99]:
# Rowvise concatanation

p.concat([df16,df17] , axis = 0)

a     b     c     d  key1   key2  key3      key4
1     1   7.0  13.0  19.0   NaN    NaN   NaN       NaN
2     2   8.0  14.0  20.0   NaN    NaN   NaN       NaN
3     3   9.0  15.0  21.0   NaN    NaN   NaN       NaN
4     4  10.0  16.0  22.0   NaN    NaN   NaN       NaN
5     5  11.0  17.0  23.0   NaN    NaN   NaN       NaN
6  sudh  12.0  18.0  24.0   NaN    NaN   NaN       NaN
1   NaN   NaN   NaN   NaN     1      7  13.0        19
2   NaN   NaN   NaN   NaN     2      8  14.0        20
3   NaN   NaN   NaN   NaN     3  kumar  15.0        21
4   NaN   NaN   NaN   NaN     4     10  16.0   ineuron
5   NaN   NaN   NaN   NaN     5     11  17.0  pwskills
F   NaN   NaN   NaN   NaN  sudh     12  18.0        24

In [104]:
d22 = {'a':[1,2,3,4,5,"sudh"],
      'b' : [7,8,9,10,11,12],
      'c':[13,14,15,16,17,18],
      'd':[19,20,21,22,23,24]
}
d23 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"ineuron","pwskills",24]
}

In [107]:
d24 = p.DataFrame(d22)

In [108]:
d25 = p.DataFrame(d23)

In [110]:
p.concat([d24 , d25 ])

a   b   c   d
0     1   7  13  19
1     2   8  14  20
2     3   9  15  21
3     4  10  16  22
4     5  11  17  23
5  sudh  12  18  24
0     1   7  13  19
1     2   8  14  20
2     3   9  15  21
3     4  10  16  22
4     5  11  17  23
5  sudh  12  18  24

In [111]:
p.concat([d24 , d25 ] , axis = 1)

a   b   c   d     a   b   c   d
0     1   7  13  19     1   7  13  19
1     2   8  14  20     2   8  14  20
2     3   9  15  21     3   9  15  21
3     4  10  16  22     4  10  16  22
4     5  11  17  23     5  11  17  23
5  sudh  12  18  24  sudh  12  18  24

In [ ]:
# Numpay is used for data manipulation , random data generation , evaluation of matrixes

In [114]:
import numpy as n 

In [115]:
l = [2,3,4,5,6,7]

In [116]:
type(l)

list

In [117]:
a = n.array(l)

In [118]:
a

array([2, 3, 4, 5, 6, 7])

In [119]:
type(a)

numpy.ndarray

In [169]:
a1 = n.array([[2,3,3] , [3,4,5]])

In [170]:
a1

array([[2, 3, 3],
       [3, 4, 5]])

In [149]:
#  a1 = n.array([[2,3,3] , [3,4,5] , [5,6,6] , [6,7,78,8]])
# we need to pass the same length of elements in the list while creating ndarray

C:\Users\mahen\AppData\Local\Temp\ipykernel_18856\4093510307.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1 = n.array([[2,3,3] , [3,4,5] , [5,6,6] , [6,7,78,8]])


In [161]:
a2 = n.array([[[22,33,32] , [63,38,43]]])

In [162]:
a2

array([[[22, 33, 32],
        [63, 38, 43]]])

In [163]:
a

array([2, 3, 4, 5, 6, 7])

In [171]:
a1

array([[2, 3, 3],
       [3, 4, 5]])

In [165]:
a2

array([[[22, 33, 32],
        [63, 38, 43]]])

In [ ]:
check the dimension 

In [166]:
a.ndim

1

In [172]:
a1.ndim

2

In [168]:
a2.ndim

3

In [ ]:
3d array is nothing but a combination of 2d arrays 

In [173]:
l2 = [23.4,3,354,35,55]

In [174]:
n.asarray(l2)
# This function is actually same as array()

array([ 23.4,   3. , 354. ,  35. ,  55. ])

In [175]:
n.matrix(l2)
# This function covert anything in the matrix form
# Thw only diff between the matrix and array that only is when we convert anything 
# into the matrix it covert it in the two dimensional form of array 

matrix([[ 23.4,   3. , 354. ,  35. ,  55. ]])

In [ ]:
# Array is a super class in numpy 
# matrix and any other things are the part of array

In [ ]:
# asanyarray() is the function which convert the nonarray into the array 
# and if we pass array inside it then it keep it as a array 

In [177]:
h = n.matrix(l2)

In [178]:
k = n.asarray(l2)

In [180]:
n.asanyarray(h)

matrix([[ 23.4,   3. , 354. ,  35. ,  55. ]])

In [181]:
n.asanyarray(k)

array([ 23.4,   3. , 354. ,  35. ,  55. ])

In [182]:
a22 = [3,4,5,66]

In [183]:
a23 = [3,4,55,2]

In [186]:
a44 = n.asanyarray(a22)

In [189]:
a55 = n.asanyarray(a23)

In [190]:
a44

array([ 3,  4,  5, 66])

In [191]:
a55

array([ 3,  4, 55,  2])

In [192]:
a44 = a55

In [193]:
a44

array([ 3,  4, 55,  2])

In [194]:
a55

array([ 3,  4, 55,  2])

In [195]:
a55[0]

3

In [197]:
a55[0] = 89

In [198]:
a55

array([89,  4, 55,  2])

In [199]:
a44

array([89,  4, 55,  2])

In [ ]:
when we makinbg changes it aslo affect the both arrays to avoid this we use copy()

In [201]:
a55= n.copy(a44)

In [202]:
a55

array([89,  4, 55,  2])

In [203]:
a44

array([89,  4, 55,  2])

In [204]:
a55[0] = 90

In [205]:
a55

array([90,  4, 55,  2])

In [206]:
a44

array([89,  4, 55,  2])

In [ ]:
in this case it not reflect the changes from where we copied the data
this the examples of deep copy and solo copy

second is the exapmle of deep copy and first is the example of shallo copy

deep copy points to the same memory and shallo copy always points to the different memory location

In [207]:
n.fromfunction(lambda i , j : i == j , ( 3  ,  4 ))
#                                       Row   Col
# It is only work for two dimensional

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [208]:
n.random.rand(2,3)

array([[0.4300282 , 0.45717494, 0.58878655],
       [0.79008645, 0.60664328, 0.50023611]])

In [209]:
n.random.rand( 2   ,  3   ,  4  )
#            Array   row    col
# This function can generate any type of dimensional array

array([[[0.5214986 , 0.38895676, 0.41110872, 0.86239436],
        [0.89332999, 0.71020917, 0.13928681, 0.7294882 ],
        [0.29120887, 0.06017635, 0.64544657, 0.75326278]],

       [[0.79416947, 0.60541564, 0.25265783, 0.85743358],
        [0.9553821 , 0.63632485, 0.6978228 , 0.50089533],
        [0.34401085, 0.75789574, 0.39295523, 0.31900699]]])

In [210]:
n.random.rand(2,3,5,6)

array([[[[0.20470429, 0.92979582, 0.48459789, 0.17562122, 0.71972449,
          0.32990234],
         [0.81508347, 0.42054773, 0.71752373, 0.66630953, 0.08313965,
          0.48236952],
         [0.76281376, 0.76568561, 0.30469919, 0.62602035, 0.99381004,
          0.75451774],
         [0.69524407, 0.55933849, 0.28863167, 0.05201028, 0.97189548,
          0.77424821],
         [0.14759294, 0.45372382, 0.94266977, 0.61582438, 0.68672395,
          0.80402992]],

        [[0.63908181, 0.07664635, 0.28927064, 0.63366103, 0.86157654,
          0.46144158],
         [0.87567391, 0.65745983, 0.69451442, 0.9869368 , 0.28361231,
          0.89165481],
         [0.95030755, 0.90742121, 0.63870979, 0.58657561, 0.99125531,
          0.68305037],
         [0.17386146, 0.59261108, 0.40633311, 0.93521542, 0.48844027,
          0.98884975],
         [0.99542893, 0.14777972, 0.5928157 , 0.72238619, 0.72107344,
          0.48416162]],

        [[0.58668152, 0.4131703 , 0.3399664 , 0.81962387, 0.076759

In [211]:
n.random.rand(3,4,4)

array([[[0.62202269, 0.89967046, 0.64655919, 0.22259452],
        [0.82005194, 0.15807237, 0.05816774, 0.05786161],
        [0.86139935, 0.45994998, 0.64459694, 0.8453628 ],
        [0.06430222, 0.30726475, 0.76002949, 0.99139186]],

       [[0.19292291, 0.49603284, 0.19193681, 0.08513123],
        [0.1898093 , 0.4258223 , 0.38578082, 0.62177918],
        [0.94646208, 0.11257838, 0.40322903, 0.76714135],
        [0.92037918, 0.2912362 , 0.65921417, 0.2256385 ]],

       [[0.60151852, 0.16679235, 0.16010224, 0.09193224],
        [0.85642911, 0.68069276, 0.67934757, 0.16892625],
        [0.04121031, 0.13105764, 0.01315195, 0.75444675],
        [0.43261606, 0.63107511, 0.28353434, 0.16035295]]])

In [213]:
n.random.randint(0,10 , (4,4))

array([[5, 1, 8, 6],
       [6, 8, 6, 9],
       [1, 7, 3, 2],
       [5, 4, 0, 1]])

In [215]:
n.random.randint(   0   ,    10    , (   4     ,   4  ,  2   )) 
#                Low_range  High_R  No_of_arrays  row   col 

array([[[8, 7],
        [7, 6],
        [5, 4],
        [9, 2]],

       [[1, 0],
        [8, 3],
        [2, 5],
        [0, 4]],

       [[8, 1],
        [6, 3],
        [4, 9],
        [5, 7]],

       [[8, 7],
        [7, 0],
        [6, 7],
        [2, 2]]])

In [220]:
d = n.random.rand(3,4)

In [221]:
p.DataFrame(d)

0         1         2         3
0  0.493747  0.611048  0.379341  0.297756
1  0.241390  0.251827  0.955970  0.295216
2  0.740717  0.951023  0.142685  0.210310

In [222]:
n.random.randint(   0   ,    10    , (   4     ,   4  ,  2   ))
#                                        4    *    4  *  2 = 32 
# To convert below into datasets into dataframe then we have to do some changes
# To make it we use reshape function 
# when we convert the dataset into the dataframe the dataset must be present into 
# two dimensional format if it is not then we have to tranform it in two dimensinal format
# by ussing this purpose 

# n.random.randint(   0   ,    10    , (   4     ,   4  ,  2   ))
#                                          4    *    4 *  2  = 32 

array([[[1, 7],
        [2, 1],
        [6, 4],
        [8, 8]],

       [[1, 9],
        [3, 3],
        [6, 3],
        [0, 9]],

       [[6, 2],
        [7, 6],
        [8, 8],
        [3, 8]],

       [[3, 5],
        [2, 9],
        [9, 3],
        [1, 9]]])

In [223]:
 k = n.random.randint(   0   ,    10    , (   4     ,   4  ,  2   ))

In [224]:
k

array([[[6, 5],
        [3, 0],
        [8, 1],
        [3, 6]],

       [[6, 6],
        [8, 9],
        [9, 5],
        [1, 4]],

       [[9, 3],
        [7, 1],
        [2, 2],
        [8, 0]],

       [[4, 5],
        [6, 4],
        [5, 3],
        [8, 3]]])

In [227]:
k.reshape(8,4)

array([[6, 5, 3, 0],
       [8, 1, 3, 6],
       [6, 6, 8, 9],
       [9, 5, 1, 4],
       [9, 3, 7, 1],
       [2, 2, 8, 0],
       [4, 5, 6, 4],
       [5, 3, 8, 3]])

In [228]:
k.reshape(16,2)

array([[6, 5],
       [3, 0],
       [8, 1],
       [3, 6],
       [6, 6],
       [8, 9],
       [9, 5],
       [1, 4],
       [9, 3],
       [7, 1],
       [2, 2],
       [8, 0],
       [4, 5],
       [6, 4],
       [5, 3],
       [8, 3]])

In [230]:
k.reshape(8,-1)
# -1 is basically used to find the missing dimension we can use any negative number over there

array([[6, 5, 3, 0],
       [8, 1, 3, 6],
       [6, 6, 8, 9],
       [9, 5, 1, 4],
       [9, 3, 7, 1],
       [2, 2, 8, 0],
       [4, 5, 6, 4],
       [5, 3, 8, 3]])

In [229]:
k.reshape(10,2)

ValueError: cannot reshape array of size 32 into shape (10,2)

In [ ]:
let's convert it into dataframe 

In [231]:
o = k.reshape(8,-1)

In [232]:
p.DataFrame(o)

0  1  2  3
0  6  5  3  0
1  8  1  3  6
2  6  6  8  9
3  9  5  1  4
4  9  3  7  1
5  2  2  8  0
6  4  5  6  4
7  5  3  8  3